#!/usr/bin/env python
#_*_ coding:utf-8 _*_

name = raw_input('Please input your name:')
age = raw_input('age:')
job = raw_input('job:')

print '''info %s
        name:%s
        age: %d
        job: %s
'''%(name,name,age,job) 
